GRANT USAGE ON SCHEMA public TO gps_guardian_app;
GRANT USAGE ON SCHEMA public TO gps_guardian_readonly;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gps_guardian_app;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO gps_guardian_readonly;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA public TO gps_guardian_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO gps_guardian_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO gps_guardian_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON ROUTINES TO gps_guardian_app;
