DROP TABLE IF EXISTS ConfiguracionSeguridad CASCADE;
DROP TABLE IF EXISTS PoliticaContrasena CASCADE;
DROP TABLE IF EXISTS SesionUsuario CASCADE;
DROP TABLE IF EXISTS Rol_Permiso CASCADE;
DROP TABLE IF EXISTS Usuario_Rol CASCADE;
DROP TABLE IF EXISTS Permiso CASCADE;
DROP TABLE IF EXISTS Rol CASCADE;
