REVOKE EXECUTE ON ALL ROUTINES IN SCHEMA public FROM gps_guardian_app;
REVOKE SELECT ON ALL TABLES IN SCHEMA public FROM gps_guardian_readonly;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM gps_guardian_app;

REVOKE USAGE ON SCHEMA public FROM gps_guardian_readonly;
REVOKE USAGE ON SCHEMA public FROM gps_guardian_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON ROUTINES FROM gps_guardian_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT ON TABLES FROM gps_guardian_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM gps_guardian_app;
